[tool.poetry.group.dev-neovim.dependencies]
neovim = "^0.3.1"
flake8 = "7.0.0"
jupyter = "^1.0.0"
pynvim = "^0.5.0"
pyproject-flake8 = "^7.0.0"



[tool.black]
line-length = 90

[tool.flake8]
max-complexity = 10
max-line-length = 90

[tool.isort]
multi_line_output = 3
line_length = 90
include_trailing_comma = true


